version: 1.0.{build}.0
skip_tags: true
image: Visual Studio 2022
build_script:
- ps: .\build_app.ps1
artifacts:
- path: Unpaint\bin\Release\x64\Unpaint_*.*
  name: MsixPackages
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_BUILD_VERSION)
  release: $(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: cJH8jFWP1GRslj2mqEaIfx/IdyTss+sj0c81d9fAXE/Eq9wCsPju+gM3CkNE0+wc
  artifact: MsixPackages