version: 1.0.{build}.0
branches:
  only:
  - main
skip_tags: true
environment:
  UNPAINT_CERT_PW:
    secure: c9UVCQE4fooTAG8lEZOxojl/EliBHDaaX1Br7ixA24i488loP3pztXfZ3zAVkuwF
image: Visual Studio 2022
build_script:
- ps: .\build_app.ps1
artifacts:
- path: Unpaint\bin\Release\x64\Unpaint_*.*
  name: MsixPackages
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_BUILD_VERSION)
  release: $(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_BUILD_VERSION)
  prerelease: true
  auth_token:
    secure: cJH8jFWP1GRslj2mqEaIfx/IdyTss+sj0c81d9fAXE/Eq9wCsPju+gM3CkNE0+wc
  artifact: MsixPackages